//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mAtencion
    {
        public int cita_id { get; set; }
        public string diagnostico { get; set; }
        public string examenes { get; set; }
        public string receta { get; set; }
    
        public virtual mCita mCita { get; set; }
    }
}
