//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mParametros
    {
        public int registro_id { get; set; }
        public string smtpserver { get; set; }
        public int smtppuerto { get; set; }
        public string correo_sistema { get; set; }
        public string clave_correo { get; set; }
    }
}
