//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mPermisos
    {
        public int registro_id { get; set; }
        public int rol_id { get; set; }
        public int modulo_id { get; set; }
        public int accion_id { get; set; }
        public bool estado { get; set; }
    
        public virtual mCatalogo mCatalogo { get; set; }
        public virtual mCatalogo mCatalogo1 { get; set; }
        public virtual mCatalogo mCatalogo2 { get; set; }
    }
}
