//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rTipo_Persona
    {
        public int registro_id { get; set; }
        public int persona_id { get; set; }
        public int tipopersona_id { get; set; }
    
        public virtual mCatalogo mCatalogo { get; set; }
        public virtual mPersona mPersona { get; set; }
    }
}
